baseURL = "http://example.org/"
languageCode = "zh-cn"
title = "旅者手札"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowToc = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "冒险日志"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    identifier = "guides"
    name = "操作指南"
    url = "/guides/"
    weight = 15

  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 20

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 30

  [[menu.main]]
    identifier = "about"
    name = "关于我"
    url = "/about/"
    weight = 40